#!/usr/bin/env bash
# Install (or refresh) the pre-commit hook that runs .agents/check.py.
#
# Default behaviour: hook fails the commit on BLOCKERS only.
# To make the hook strict (warnings = fail), export STRICT_AGENT_CHECK=1
# in your shell, OR pass --strict to this installer.
#
# The hook is idempotent — re-running this script just replaces the file.
# Uninstall via: rm .git/hooks/pre-commit
#
# Usage:
#   .agents/install-hook.sh             # default (blockers only)
#   .agents/install-hook.sh --strict    # warnings also fail
#   .agents/install-hook.sh --uninstall # remove hook

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"

if [ ! -d "$REPO_ROOT/.git" ]; then
  echo "error: not a git repository ($REPO_ROOT/.git missing)" >&2
  exit 2
fi

if [ "${1:-}" = "--uninstall" ]; then
  if [ -f "$HOOK_PATH" ]; then
    rm "$HOOK_PATH"
    echo "✓ removed $HOOK_PATH"
  else
    echo "no hook installed at $HOOK_PATH"
  fi
  exit 0
fi

STRICT_FLAG=""
if [ "${1:-}" = "--strict" ] || [ "${STRICT_AGENT_CHECK:-0}" = "1" ]; then
  STRICT_FLAG="--strict"
fi

cat > "$HOOK_PATH" <<HOOK
#!/usr/bin/env bash
# Auto-generated by .agents/install-hook.sh — do not hand-edit.
# Runs .agents/check.py on every commit.
#
# check.py exit codes:
#   0 = clean
#   1 = warnings (advisory)
#   2 = blockers (always fails commit)
#
# In default mode, only exit code 2 (blockers) blocks the commit.
# In strict mode (.agents/install-hook.sh --strict), exit code 1+ blocks.
#
# Skip for one commit (rare): git commit --no-verify
# Refresh this hook:           .agents/install-hook.sh
# Uninstall:                   .agents/install-hook.sh --uninstall

REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
CHECK="\$REPO_ROOT/.agents/check.py"

if [ ! -x "\$CHECK" ]; then
  echo "  (.agents/check.py missing or non-executable — skipping)" >&2
  exit 0
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "  (python3 not found — skipping .agents/check)" >&2
  exit 0
fi

cd "\$REPO_ROOT"
# Run check; don't let non-zero exit kill the script — we inspect rc ourselves
set +e
python3 .agents/check.py $STRICT_FLAG
rc=\$?
set -e

# Threshold: strict mode treats warnings (rc=1) as failure too;
# default mode only fails on blockers (rc=2).
THRESHOLD=$( [ -n "$STRICT_FLAG" ] && echo 1 || echo 2 )

if [ \$rc -ge \$THRESHOLD ]; then
  echo "" >&2
  echo "  ↑ .agents/check.py failed (rc=\$rc, threshold=\$THRESHOLD); commit blocked." >&2
  echo "  Override (use sparingly): git commit --no-verify" >&2
  exit 1
fi

exit 0
HOOK

chmod +x "$HOOK_PATH"

echo "✓ installed pre-commit hook at $HOOK_PATH"
if [ -n "$STRICT_FLAG" ]; then
  echo "  mode: --strict (warnings will block commits)"
else
  echo "  mode: default (only blockers fail; warnings advisory)"
fi
echo ""
echo "  Test it now: python3 .agents/check.py"
echo "  Skip the hook for one commit: git commit --no-verify"
echo "  Uninstall later: .agents/install-hook.sh --uninstall"
