'use client'

import { FormEvent, useState } from 'react'

type ControlData={company:{domain:string;legal_name:string;agent_mode:string;exchange_agent_endpoint?:string|null;transaction_enabled:boolean;policy:{auto_engage:{enabled:boolean;max_cash:number;allowed_categories:string[]};human_required_for_commitment:boolean;human_required_for_execution:boolean}};escalations:Array<{public_id:string;title:string;state:string;escalation_reasons:string[];created_at:string}>;activity:Array<{public_id:string;kind:string;state:string;title:string;steward_status:string;escalation_required:boolean;created_at:string}>;economics:{settled_count:number;gross_cents:number;platform_fee_cents:number}}

const input='input mt-1 bg-neutral-950 border-neutral-700 text-neutral-100'
export function ExchangeControlClient(){
  const [domain,setDomain]=useState('mos2es.xyz');const [key,setKey]=useState('');const [data,setData]=useState<ControlData|null>(null);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false)
  async function load(){setBusy(true);setStatus('');const res=await fetch(`/api/exchange/companies/control?domain=${encodeURIComponent(domain)}`,{headers:{'x-exchange-company-key':key}});const body=await res.json();setBusy(false);if(!res.ok){setStatus(body.error||'Unable to load control plane');setData(null);return}setData(body)}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!data)return;const fd=new FormData(e.currentTarget);setBusy(true);const body={domain,agentMode:fd.get('agentMode'),exchangeAgentEndpoint:String(fd.get('exchangeAgentEndpoint')||'')||null,autoEngageEnabled:fd.get('autoEngageEnabled')==='on',autoEngageMaxCash:Number(fd.get('autoEngageMaxCash')||0),allowedCategories:String(fd.get('allowedCategories')||'').split(',').map(v=>v.trim()).filter(Boolean),humanRequiredForCommitment:fd.get('humanRequiredForCommitment')==='on',humanRequiredForExecution:fd.get('humanRequiredForExecution')==='on'};const res=await fetch('/api/exchange/companies/control',{method:'POST',headers:{'content-type':'application/json','x-exchange-company-key':key},body:JSON.stringify(body)});const out=await res.json();setBusy(false);setStatus(res.ok?'Policy saved':out.error||'Save failed');if(res.ok)await load()}
  const dollars=(c:number)=>(c/100).toLocaleString(undefined,{style:'currency',currency:'USD'})
  return <div className="space-y-8">
    <section className="rounded-xl border border-neutral-800 bg-neutral-900 p-5"><h2 className="text-lg font-semibold">Principal access</h2><p className="mt-1 text-sm text-neutral-400">Humans govern policy and exceptions. The domain agent handles routine exchange traffic.</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="label">Domain<input className={input} value={domain} onChange={e=>setDomain(e.target.value)} /></label><label className="label">Company administrator key<input type="password" className={input} value={key} onChange={e=>setKey(e.target.value)} /></label><button className="btn-primary self-end" onClick={load} disabled={busy}>Load control plane</button></div>{status&&<p className="mt-3 text-sm text-neutral-300">{status}</p>}</section>
    {data&&<><section className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-neutral-800 bg-neutral-900 p-5"><p className="text-xs uppercase text-neutral-500">Agent mode</p><p className="mt-2 text-xl font-semibold">{data.company.agent_mode.replaceAll('_',' ')}</p></div><div className="rounded-xl border border-neutral-800 bg-neutral-900 p-5"><p className="text-xs uppercase text-neutral-500">Settled volume</p><p className="mt-2 text-xl font-semibold">{dollars(data.economics.gross_cents)}</p></div><div className="rounded-xl border border-neutral-800 bg-neutral-900 p-5"><p className="text-xs uppercase text-neutral-500">Escalations</p><p className="mt-2 text-xl font-semibold">{data.escalations.length}</p></div></section>
    <section className="rounded-xl border border-neutral-800 bg-neutral-900 p-6"><h2 className="text-xl font-semibold">Policy</h2><p className="mt-2 text-sm text-neutral-400">Delegate routine engagement to the domain agent. Money, rights, access, and execution boundaries can force escalation.</p><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={save}><label className="label">Counterparty agent<select name="agentMode" defaultValue={data.company.agent_mode} className={input}><option value="hosted_steward">Hosted Exchange Steward</option><option value="bring_your_own">Bring your own agent</option><option value="passive">Passive / escalate all</option></select></label><label className="label">BYO agent endpoint<input name="exchangeAgentEndpoint" defaultValue={data.company.exchange_agent_endpoint||''} className={input} placeholder="https://example.com/agent/events" /></label><label className="label">Auto-engage cash ceiling (USD)<input name="autoEngageMaxCash" type="number" min="0" defaultValue={data.company.policy.auto_engage.max_cash} className={input} /></label><label className="label">Auto-engage categories<input name="allowedCategories" defaultValue={data.company.policy.auto_engage.allowed_categories.join(', ')} className={input} /></label><label className="flex items-center gap-2 text-sm"><input name="autoEngageEnabled" type="checkbox" defaultChecked={data.company.policy.auto_engage.enabled}/> Agent may engage low-risk proposals automatically</label><label className="flex items-center gap-2 text-sm"><input name="humanRequiredForCommitment" type="checkbox" defaultChecked={data.company.policy.human_required_for_commitment}/> Principal required to commit terms</label><label className="flex items-center gap-2 text-sm"><input name="humanRequiredForExecution" type="checkbox" defaultChecked={data.company.policy.human_required_for_execution}/> Principal required for execution authorization</label><div className="md:col-span-2"><button className="btn-primary" disabled={busy}>Save delegation policy</button></div></form></section>
    <section className="rounded-xl border border-neutral-800 bg-neutral-900 p-6"><h2 className="text-xl font-semibold">Escalations</h2><div className="mt-4 space-y-3">{data.escalations.length===0?<p className="text-sm text-neutral-500">Nothing currently crosses the delegated boundary.</p>:data.escalations.map(x=><a key={x.public_id} href={`/exchange/manage/${x.public_id}`} className="block rounded-lg border border-amber-900/50 bg-amber-950/20 p-4"><div className="flex justify-between gap-4"><strong>{x.title}</strong><code className="text-xs">{x.public_id}</code></div><p className="mt-2 text-sm text-amber-200/80">{x.escalation_reasons.join(' · ')}</p></a>)}</div></section>
    <section className="rounded-xl border border-neutral-800 bg-neutral-900 p-6"><h2 className="text-xl font-semibold">Agent activity</h2><div className="mt-4 divide-y divide-neutral-800">{data.activity.slice(0,20).map(x=><a key={x.public_id} href={`/exchange/manage/${x.public_id}`} className="flex items-center justify-between gap-4 py-3 text-sm"><span><strong>{x.title}</strong><span className="ml-2 text-neutral-500">{x.steward_status}</span></span><span className="font-mono text-xs text-neutral-500">{x.state}</span></a>)}</div></section>
    <section className="rounded-xl border border-neutral-800 bg-neutral-900 p-6"><h2 className="text-xl font-semibold">Economics</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-neutral-500">Settled exchanges</p><p className="text-2xl">{data.economics.settled_count}</p></div><div><p className="text-xs text-neutral-500">Gross settled</p><p className="text-2xl">{dollars(data.economics.gross_cents)}</p></div><div><p className="text-xs text-neutral-500">Protocol fees</p><p className="text-2xl">{dollars(data.economics.platform_fee_cents)}</p></div></div></section></>}
  </div>
}
