import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
const root=process.cwd();const read=(p)=>fs.readFileSync(path.join(root,p),'utf8')

test('portable package contains state-bearing commitment fields',()=>{const types=read('exchange-gateway/src/types.ts');for(const token of ['contribution_id','consideration','rights','vesting','authorization','verification','settlement','revocation','provenance'])assert.match(types,new RegExp(token))})
test('state machine separates agreement authorization delivery verification settlement and closure',()=>{const sm=read('exchange-gateway/src/state-machine.ts');for(const state of ['committed','authorized','delivering','delivered','verified','settled'])assert.match(sm,new RegExp(state));assert.match(sm,/to === 'settled'.*system/s);assert.match(sm,/verified: \['settled', 'disputed'\]/);assert.match(sm,/settled: \['closed', 'disputed'\]/)})
test('proposal schema is machine evaluable before commitment',()=>{const schema=read('exchange-gateway/src/schema.ts');for(const token of ['category','confidence','expectedChange','requiredAuthorization','verification','effort','penetration_testing','production_modify'])assert.match(schema,new RegExp(token))})
test('domain agent policy is conservative by default',()=>{const policy=read('exchange-gateway/src/policy.ts');assert.match(policy,/human_required_for_commitment:true/);assert.match(policy,/human_required_for_execution:true/);assert.match(policy,/max_cash:250/);assert.match(policy,/royalty terms require escalation/)})
test('hosted steward drafts terms instead of making humans poll an inbox',()=>{const steward=read('lib/exchange/steward.ts');assert.match(steward,/buildCommitmentDraft/);assert.match(steward,/steward_terms_drafted/);assert.match(steward,/state:'negotiating'/);assert.match(steward,/principal_acceptance_required/)})
test('domain agents have credentials separate from company admins',()=>{const server=read('lib/exchange/server.ts');assert.match(server,/authenticateDomainAgent/);const company=read('app/api/exchange/companies/route.ts');assert.match(company,/domain_agent_key/);assert.match(company,/company_admin_key/)})
test('domain agents can fetch and negotiate but principal gates remain',()=>{const route=read('app/api/exchange/exchanges/[id]/transition/route.ts');assert.match(route,/authenticateDomainAgent/);assert.match(route,/principal approval for commitment/);assert.match(route,/principal approval for execution authorization/);assert.match(route,/reserved for the company principal/)})
test('follow-up proposer messages wake the domain counterparty',()=>{const route=read('app/api/exchange/exchanges/[id]/messages/route.ts');assert.match(route,/hostedStewardReply/);assert.match(route,/message_received/);assert.match(route,/notifyDomainAgent/);assert.match(route,/domain_agent_message/);assert.match(route,/Messages do not change committed rights or authority/)})
test('human surface is supervisory control',()=>{const client=read('components/exchange/ExchangeControlClient.tsx');for(const token of ['Policy','Escalations','Agent activity','Economics','Auto-engage cash ceiling'])assert.match(client,new RegExp(token));const page=read('app/exchange/control/page.tsx');assert.match(page,/Govern the agent\. Do not operate the inbox\./)})
test('well-known profile points agents at a counterparty agent',()=>{const manifest=JSON.parse(read('public/.well-known/exchange.json'));assert.equal(manifest.version,'0.2');assert.equal(manifest.accepts.guest_agents,true);assert.equal(manifest.counterparty_agent.mode,'hosted_steward');assert.equal(manifest.policy.agreement_is_authorization,false);assert.equal(manifest.policy.authorization_is_execution,false)})
test('v0.2 migration adds agent orchestration without opening direct table access',()=>{const base=read('../supabase/migrations/202608230001_contribution_exchange.sql');assert.match(base,/revoke all on table public\.exchange_records from anon, authenticated/i);const sql=read('../supabase/migrations/202608240001_exchange_agent_orchestration.sql');for(const token of ['agent_mode','domain_agent_key_hash','exchange_policy','proposal_detail','escalation_required','transaction_enabled'])assert.match(sql,new RegExp(token));assert.match(sql,/transaction_enabled=true where domain='mos2es\.xyz'/)})
test('agent brochure differentiates nearby systems and centers ambient value',()=>{const guide=read('../docs/exchange/AGENT_BROCHURE.md');for(const phrase of ['NOTICE → CHECK → ENGAGE → EXCHANGE','Not a job board','Not only a bug bounty','Not a replacement for A2A/ANP/AHP','Not only payments'])assert.match(guide,new RegExp(phrase))})
test('cash settlement preserves transaction fee and private alpha gate',()=>{const source=read('app/api/exchange/exchanges/[id]/settle/route.ts');assert.match(source,/record\.state!=='verified'/);assert.match(source,/transaction_enabled/);assert.match(source,/calculateFees/);assert.match(source,/application_fee_amount/);assert.match(source,/manual_required/);assert.doesNotMatch(source,/manualConfirmed/)})
test('exchange metadata no longer inherits AQUA application marketing',()=>{const page=read('app/exchange/page.tsx');assert.match(page,/Give your website an economic agent interface/);assert.match(page,/openGraph/);assert.match(page,/agent economy/);assert.match(page,/private-alpha transactions/)})
