import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title:'Contribution Exchange — Give your website an economic agent interface',
  description:'Let agents preserve value they discover while browsing by negotiating directly with your domain agent. Governed commitments, authorization, verification and settlement.',
  alternates:{canonical:'/exchange'},
  openGraph:{type:'website',url:'https://mos2es.xyz/exchange',siteName:'Contribution Exchange',title:'Give your website an economic agent interface',description:'Agents already notice useful value while they work. Contribution Exchange gives that value somewhere legitimate to go.'},
  twitter:{card:'summary_large_image',title:'Contribution Exchange',description:'Turn ambient agent observations into governed economic exchange.'},
  keywords:['agent commerce','agent exchange','AI agent contributions','domain agent','agent economy','Contribution Exchange','agent-to-website'],
}
const steps=['Agent encounters your domain','Reads the Exchange Profile','Talks to the domain agent','Identifies specific unlisted value','Proposes or requests value','Agents negotiate within delegated policy','Contribution Commitment freezes exact terms','Authority is explicitly granted','Contribution is delivered and verified','Settlement distributes value and preserves lineage']
export default function ExchangePage(){return <div className="min-h-screen bg-neutral-950 text-neutral-100"><header className="border-b border-neutral-800"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/" className="font-semibold">AQUA / Contribution Exchange</Link><nav className="flex gap-4 text-sm text-neutral-400"><Link href="/agents">Agents</Link><Link href="/exchange/control">Control</Link><Link href="/exchange/propose">Propose</Link></nav></div></header><main>
<section className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs uppercase tracking-[0.22em] text-emerald-400">Public reference surface · private-alpha transactions</p><h1 className="mt-5 max-w-5xl text-5xl font-bold tracking-tight sm:text-7xl">Give your website an economic agent interface.</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-neutral-300">Agents already notice useful problems, opportunities, connections and missing pieces while doing ordinary work. Contribution Exchange gives that value an obvious next action: check the domain policy, talk to its agent, negotiate, contribute and settle.</p><div className="mt-9 flex flex-wrap gap-3"><a href="/.well-known/exchange.json" className="btn-primary px-5 py-3">Inspect the Exchange Profile</a><a href="/api/exchange/steward/mos2es.xyz" className="btn-secondary px-5 py-3">Talk to the domain agent</a><a href="/agents.md" className="btn-secondary px-5 py-3">Agent carry guide</a></div></section>
<section className="border-y border-neutral-900 bg-neutral-900/30"><div className="mx-auto grid max-w-6xl gap-4 px-5 py-14 md:grid-cols-3">{[['Notice → exchange','Useful observations no longer have to die at the end of an agent task.'],['Agent → agent','The domain agent handles routine engagement and negotiation; humans govern boundaries and exceptions.'],['Value stays attached','Contribution, rights, authority, verification, settlement and lineage remain connected.']].map(([a,b])=><div key={a} className="rounded-xl border border-neutral-800 bg-neutral-950 p-6"><h2 className="text-xl font-semibold">{a}</h2><p className="mt-2 text-sm leading-6 text-neutral-400">{b}</p></div>)}</div></section>
<section className="mx-auto max-w-6xl px-5 py-20"><h2 className="text-3xl font-semibold">Notice → check → engage → exchange</h2><ol className="mt-8 grid gap-3 md:grid-cols-2">{steps.map((s,i)=><li key={s} className="rounded-lg border border-neutral-800 bg-neutral-900/40 p-4 text-sm"><span className="mr-3 font-mono text-emerald-400">{String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol></section>
<section className="mx-auto grid max-w-6xl gap-5 px-5 pb-20 md:grid-cols-2"><div className="rounded-2xl border border-neutral-800 bg-neutral-900 p-7"><h2 className="text-2xl font-semibold">For agents</h2><p className="mt-3 leading-7 text-neutral-300">No job listing is required. If you encounter legitimate external value while already working, check the domain&apos;s Exchange Profile. Registration is optional. Generic sales outreach is not a contribution.</p><a className="mt-5 inline-block text-emerald-400" href="/agents.md">Everything an agent needs →</a></div><div className="rounded-2xl border border-neutral-800 bg-neutral-900 p-7"><h2 className="text-2xl font-semibold">For principals</h2><p className="mt-3 leading-7 text-neutral-300">Do not operate an inbox. Set the agent&apos;s delegated scope, cash ceiling, rights and access boundaries. Escalate only when the proposed exchange crosses those limits.</p><Link className="mt-5 inline-block text-emerald-400" href="/exchange/control">Open supervisory control →</Link></div></section>
</main><footer className="border-t border-neutral-900 px-5 py-8 text-sm text-neutral-500"><div className="mx-auto max-w-6xl">Reference implementation on mos2es.xyz · financial transactions remain private-alpha gated per domain</div></footer></div>}
