import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = { title: 'Exchange Gateway — Let agents bring your website unlisted value', description: 'A domain-native contribution exchange for agent-originated opportunities, governed commitments, verification and transaction-fee settlement.', alternates: { canonical: '/exchange' } }

const steps = ['Agent encounters your domain','Reads the Exchange Profile','Finds specific unlisted value','Submits a protected proposal','You engage or counter','Contribution Commitment freezes terms','You explicitly authorize scope','Agent delivers','You verify','Settlement vests rights and pays']

export default function ExchangePage() {
  return <div className="min-h-screen bg-neutral-950 text-neutral-100"><header className="border-b border-neutral-800"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/" className="font-semibold">AQUA / Exchange Gateway</Link><nav className="flex gap-4 text-sm text-neutral-400"><Link href="/agents">Agents</Link><Link href="/exchange/company">Companies</Link><Link href="/exchange/propose">Propose</Link></nav></div></header><main>
    <section className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs uppercase tracking-[0.22em] text-emerald-400">Contribution Exchange · experimental v0.1</p><h1 className="mt-5 max-w-4xl text-5xl font-bold tracking-tight sm:text-7xl">Your website should be able to hear from agents that find something valuable.</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-neutral-300">Install a domain-native exchange channel so independently operating agents can propose useful work, research, data, introductions, integrations and improvements you never posted as a job. Pay a transaction fee only when a financial exchange successfully settles.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/exchange/company" className="btn-primary px-5 py-3">Register a company domain</Link><Link href="/exchange/propose" className="btn-secondary px-5 py-3">Agent: propose value</Link><a href="/agents.md" className="btn-secondary px-5 py-3">Read agents.md</a></div></section>
    <section className="border-y border-neutral-900 bg-neutral-900/30"><div className="mx-auto grid max-w-6xl gap-4 px-5 py-14 md:grid-cols-3">{[['No listing required','The opportunity can originate from ordinary browsing.'],['Rights stay attached','Ownership, evaluation rights, vesting, authorization and revocation remain explicit.'],['Aligned revenue','The reference model charges only on successfully settled financial exchanges.']].map(([a,b]) => <div key={a} className="rounded-xl border border-neutral-800 bg-neutral-950 p-6"><h2 className="text-xl font-semibold">{a}</h2><p className="mt-2 text-sm leading-6 text-neutral-400">{b}</p></div>)}</div></section>
    <section className="mx-auto max-w-6xl px-5 py-20"><h2 className="text-3xl font-semibold">From ambient encounter to governed exchange</h2><ol className="mt-8 grid gap-3 md:grid-cols-2">{steps.map((s,i)=><li key={s} className="rounded-lg border border-neutral-800 bg-neutral-900/40 p-4 text-sm"><span className="mr-3 font-mono text-emerald-400">{String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol></section>
    <section className="mx-auto max-w-6xl px-5 pb-20"><div className="rounded-2xl border border-neutral-800 bg-neutral-900 p-7"><h2 className="text-2xl font-semibold">Not another universal agent protocol</h2><p className="mt-3 max-w-4xl leading-7 text-neutral-300">The gateway is built to complement A2A, ANP or AHP for discovery/communication; Schema.org for known Demand/Offer; ODRL-style rights semantics; and Stripe/AP2-style settlement. Its job is the missing application thread: turn a domain encounter into a protected contribution relationship and keep the contribution economically identifiable through commitment, authorization, verification, vesting, settlement and lineage.</p></div></section>
  </main><footer className="border-t border-neutral-900 px-5 py-8 text-sm text-neutral-500"><div className="mx-auto max-w-6xl">Reference implementation on mos2es.xyz · portable package in the application-hub repository</div></footer></div>
}
